import {
  AREA_HEADS,
  AREA_LABELS,
  type CaseFile,
  type Notification,
  type Priority,
  type Stage,
  type TimelineEvent,
  type ActivityComment,
} from "./types";
import { uid } from "./utils";

function daysAgo(n: number, h = 9, m = 0): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  d.setHours(h, m, 0, 0);
  return d.toISOString();
}

function daysAhead(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() + n);
  d.setHours(18, 0, 0, 0);
  return d.toISOString();
}

function ev(
  kind: TimelineEvent["kind"],
  days: number,
  actor: string,
  actorRole: TimelineEvent["actorRole"],
  title: string,
  detail?: string
): TimelineEvent {
  return {
    id: uid("ev"),
    kind,
    at: daysAgo(days, 9 + (Math.abs(days) % 6)),
    actor,
    actorRole,
    title,
    detail,
  };
}

export const SEED_CASES: CaseFile[] = [
  {
    id: "SOP-20-2026",
    type: "incidente",
    title: "Falla en sistema de puertas de andén estación Javier Prado",
    description:
      "Puerta de andén 4 no cierra correctamente, permanece entreabierta 5cm. Riesgo de caída de pasajeros a vía. Detectado por conductor durante parada programada.",
    observations: "Sensor de posición muestra lectura errática. Actuador neumático con fuga leve.",
    area: "mr",
    station: "Javier Prado",
    location: "Andén · puerta 4",
    date: daysAgo(15, 10, 20).slice(0, 10),
    time: "10:20",
    priority: "alta",
    riskLevel: "2C",
    stage: "cierre",
    reporter: "Carlos Mendoza",
    reporterRole: "reportante",
    assignee: AREA_HEADS.mr,
    assigneeArea: "mr",
    evidence: [
      { id: uid("ev"), kind: "foto", name: "puerta_falla_1.jpg", size: "2.8 MB", at: daysAgo(15, 10, 25) },
      { id: uid("ev"), kind: "foto", name: "puerta_falla_2.jpg", size: "3.1 MB", at: daysAgo(15, 10, 27) },
      { id: uid("ev"), kind: "video", name: "puerta_operacion.mp4", size: "15.4 MB", at: daysAgo(15, 10, 30) },
    ],
    timeline: [
      ev("creado", 15, "Carlos Mendoza", "reportante", "Reporte registrado por conductor de tren"),
      ev("aprobado", 14, "M. Falcón", "seguridad", "Caso aprobado por Seguridad Operativa"),
      ev("derivado", 14, "M. Falcón", "seguridad", `Derivado a ${AREA_HEADS.mr} · ${AREA_LABELS.mr}`),
      ev("investigacion", 12, AREA_HEADS.mr, "reportante", "Investigación completada", "Sensor de posición defectuoso + actuador con fuga"),
      ev("plan_propuesto", 10, AREA_HEADS.mr, "reportante", "Plan de acción propuesto", "Reemplazo de sensor y actuador"),
      ev("plan_aprobado", 9, "M. Falcón", "seguridad", "Plan aprobado por Seguridad Operativa"),
      ev("ejecucion", 5, AREA_HEADS.mr, "reportante", "Ejecución completada", "Sensor y actuador reemplazados"),
      ev("seguimiento", 3, "M. Falcón", "seguridad", "Verificación realizada", "Funcionamiento correcto verificado"),
      ev("cierre", 1, "M. Falcón", "seguridad", "Caso cerrado", "Historial completo archivado"),
    ],
    investigation: {
      technicalDescription: "Puerta de andén modelo Siemens, serie 2018. Sensor de posición tipo inductivo. Actuador neumático Festo.",
      findings: "Sensor de posición con circuito interno dañado por sobrecarga eléctrica. Actuador neumático con fuga en sello principal.",
      rootCause: "Sobrecarga eléctrica por variación de tensión + desgaste de sello por uso prolongado sin mantenimiento preventivo.",
      conclusions: "Requiere reemplazo de sensor y actuador. Implementar mantenimiento preventivo trimestral.",
      observations: "Extender inspección a puertas 2, 3 y 5 de misma estación.",
      updatedAt: daysAgo(12, 14, 0),
    },
    actionPlans: [
      {
        elaboratedBy: "Marcela Falcón",
        actionType: "Correctiva",
        description: "Reemplazo de sensor de posición y actuador neumático en puerta de andén 4. Implementación de mantenimiento preventivo.",
        startDate: daysAgo(10).slice(0, 10),
        dueDate: daysAgo(5).slice(0, 10),
        estimatedTime: "5 días",
        priority: "alta" as Priority,
        observations: "Coordinar con Operaciones para ventana de mantenimiento nocturno (00:00-04:00).",
        sentToArea: "mr",
        items: [
          { id: uid("ai"), name: "Adquisición de sensor de posición", description: "Solicitar sensor inductivo Siemens equivalente", owner: AREA_HEADS.mr, priority: "alta" as Priority, startDate: daysAgo(10).slice(0, 10), dueDate: daysAgo(9).slice(0, 10), progress: 100, status: "completado", comments: [{ id: uid("comment"), text: "Sensor recibido en almacén", author: AREA_HEADS.mr, at: daysAgo(9) }] },
          { id: uid("ai"), name: "Adquisición de actuador neumático", description: "Solicitar actuador Festo equivalente", owner: AREA_HEADS.mr, priority: "alta" as Priority, startDate: daysAgo(10).slice(0, 10), dueDate: daysAgo(9).slice(0, 10), progress: 100, status: "completado", comments: [{ id: uid("comment"), text: "Actuador recibido en almacén", author: AREA_HEADS.mr, at: daysAgo(9) }] },
          { id: uid("ai"), name: "Desmontaje de componentes defectuosos", description: "Retirar sensor y actuador dañados", owner: AREA_HEADS.mr, priority: "alta" as Priority, startDate: daysAgo(8).slice(0, 10), dueDate: daysAgo(8).slice(0, 10), progress: 100, status: "completado", comments: [{ id: uid("comment"), text: "Componentes retirados sin incidentes", author: AREA_HEADS.mr, at: daysAgo(8) }] },
          { id: uid("ai"), name: "Instalación de nuevos componentes", description: "Instalar sensor y actuador nuevos", owner: AREA_HEADS.mr, priority: "alta" as Priority, startDate: daysAgo(7).slice(0, 10), dueDate: daysAgo(6).slice(0, 10), progress: 100, status: "completado", comments: [{ id: uid("comment"), text: "Instalación completada", author: AREA_HEADS.mr, at: daysAgo(6) }] },
          { id: uid("ai"), name: "Pruebas de funcionamiento", description: "Verificar operación correcta de puerta", owner: AREA_HEADS.mr, priority: "alta" as Priority, startDate: daysAgo(6).slice(0, 10), dueDate: daysAgo(5).slice(0, 10), progress: 100, status: "completado", comments: [{ id: uid("comment"), text: "50 ciclos de prueba OK", author: AREA_HEADS.mr, at: daysAgo(5) }] },
        ],
        submittedAt: daysAgo(10, 16, 0),
        reviewedAt: daysAgo(9, 9, 30),
        reviewDecision: "aprobado",
      },
    ],
    execution: {
      progress: 100,
      acceptedByAreaAt: daysAgo(9, 10, 0),
      updates: [
        { id: uid("ex"), at: daysAgo(9, 16, 0), author: AREA_HEADS.mr, progress: 20, comment: "Componentes recibidos. Inicio desmontaje." },
        { id: uid("ex"), at: daysAgo(8, 11, 0), author: AREA_HEADS.mr, progress: 40, comment: "Componentes defectuosos retirados." },
        { id: uid("ex"), at: daysAgo(7, 17, 0), author: AREA_HEADS.mr, progress: 80, comment: "Nuevos componentes instalados. Inicio pruebas." },
        { id: uid("ex"), at: daysAgo(5, 18, 0), author: AREA_HEADS.mr, progress: 100, comment: "50 ciclos de prueba completados. Funcionamiento OK." },
      ],
    },
    slaDueDate: daysAgo(2),
    createdAt: daysAgo(15),
    closedAt: daysAgo(1, 16, 0),
  },
  {
    id: "SOP-19-2026",
    type: "accidente",
    title: "Caída de pasajero en escalera mecánica estación San Juan de Dios",
    description:
      "Pasajero adulto mayor tropezó en escalera mecánica sur debido a desperfecto en pasamanos. Presentó contusión leve en hombro derecho. Personal de seguridad brindó primeros auxilios.",
    observations:
      "Pasamanos presentaba holgura excesiva en tramo intermedio. Mantenimiento preventivo vencido desde hace 15 días.",
    area: "mantenimiento",
    station: "San Juan de Dios",
    location: "Escalera mecánica sur · nivel 1",
    date: daysAgo(1, 8, 15).slice(0, 10),
    time: "08:15",
    priority: "critica",
    riskLevel: "1A",
    stage: "recepcion",
    reporter: "Miguel Ángel Huamán",
    reporterRole: "reportante",
    assignee: AREA_HEADS.mantenimiento,
    assigneeArea: "mantenimiento",
    evidence: [
      { id: uid("ev"), kind: "foto", name: "escalera_falla_1.jpg", size: "3.2 MB", at: daysAgo(1, 8, 20) },
      { id: uid("ev"), kind: "foto", name: "escalera_falla_2.jpg", size: "2.8 MB", at: daysAgo(1, 8, 22) },
      { id: uid("ev"), kind: "documento", name: "reporte_seguridad.pdf", size: "890 KB", at: daysAgo(1, 9, 0) },
    ],
    timeline: [
      ev("creado", 1, "Miguel Ángel Huamán", "reportante", "Reporte registrado por personal de seguridad"),
    ],
    evento: {
      rangoHorario: "08:00 - 08:59",
      tipoIncidenteOperativo: "caida_pasajero",
      descripcionEvento: "Pasajero tropezó en escalera mecánica por pasamanos defectuoso.",
      ubicacion: "estacion",
      tipoVia: "par",
      lugarIncidente: "SJD",
      modeloMR: "N/A",
      nroMR: "N/A",
      personalFalla: "pasajero",
      tipoCausa: "falla_equipamiento",
      posibleCausa: "Falla mecánica",
      informacionAdicional: "Escalera mecánica modelo Mitsubishi, serie 2019.",
    },
    slaDueDate: daysAhead(2),
    createdAt: daysAgo(1),
  },
  {
    id: "SOP-17-2026",
    type: "falla_operativa",
    title: "Falla en sistema de frenado de tren 102 en estación Miguel Grau",
    description:
      "Tren 102 presentó activación de freno de emergencia sin comando en estación Miguel Grau. Pasajeros evacuados por vía de emergencia. Servicio suspendido 25 minutos en tramo central.",
    observations: "Sensor de velocidad en bogie 2 mostró lectura errónea. Sistema de diagnóstico activó freno de seguridad.",
    area: "material_rodante",
    station: "Miguel Grau",
    location: "Vía 1 · andén norte",
    date: daysAgo(3, 16, 45).slice(0, 10),
    time: "16:45",
    priority: "critica",
    riskLevel: "1A",
    stage: "investigacion",
    reporter: "Jorge Luis Sánchez",
    reporterRole: "reportante",
    assignee: AREA_HEADS.material_rodante,
    assigneeArea: "material_rodante",
    evidence: [
      { id: uid("ev"), kind: "video", name: "falla_freno.mp4", size: "24.5 MB", at: daysAgo(3, 16, 50) },
      { id: uid("ev"), kind: "documento", name: "log_tren102.xlsx", size: "456 KB", at: daysAgo(2, 10, 0) },
    ],
    timeline: [
      ev("creado", 3, "Jorge Luis Sánchez", "reportante", "Reporte de conductor de tren"),
      ev("aprobado", 2, "M. Falcón", "seguridad", "Caso aprobado por Seguridad Operativa"),
      ev("derivado", 2, "M. Falcón", "seguridad", `Derivado a ${AREA_HEADS.material_rodante} · ${AREA_LABELS.material_rodante}`),
      ev("investigacion", 1, AREA_HEADS.material_rodante, "reportante", "Investigación iniciada", "Revisión de sensores y sistema de frenado."),
    ],
    investigation: {
      technicalDescription: "Tren 102, serie Alstom Metropolis 2015. Bogie 2, sensor de velocidad tipo Hall-effect.",
      findings: "Sensor de velocidad en bogie 2 con cableado deteriorado por vibración excesiva. Lecturas erráticas activaron freno de seguridad.",
      rootCause: "Fatiga de cableado por vibración no mitigada. Falta de amortiguación adecuada en instalación.",
      conclusions: "Reemplazo de cableado con especificación mejorada. Revisión preventiva en trenes 101-110.",
      observations: "Extender inspección a trenes de misma serie. Coordinar con fabricante para mejora de diseño.",
      updatedAt: daysAgo(1, 14, 0),
    },
    slaDueDate: daysAhead(4),
    createdAt: daysAgo(3),
  },
  {
    id: "SOP-16-2026",
    type: "condicion_insegura",
    title: "Fuga de agua en túnel entre estaciones Angamos y San Borja",
    description:
      "Detectada filtración de agua en pared norte del túnel, aproximadamente 150m al norte de Angamos. Flujo constante afectando vía 2. Riesgo de corrosión en rieles.",
    observations: "Posible origen en tubería de drenaje de superficie. Zona de alta afluencia vehicular.",
    area: "infraestructura",
    station: "Angamos",
    location: "Túnel · tramo Angamos–San Borja",
    date: daysAgo(5, 11, 30).slice(0, 10),
    time: "11:30",
    priority: "alta",
    riskLevel: "2C",
    stage: "plan_accion",
    reporter: "Carlos Eduardo Flores",
    reporterRole: "reportante",
    assignee: AREA_HEADS.infraestructura,
    assigneeArea: "infraestructura",
    evidence: [
      { id: uid("ev"), kind: "foto", name: "fuga_tunel_1.jpg", size: "4.1 MB", at: daysAgo(5, 11, 35) },
      { id: uid("ev"), kind: "foto", name: "fuga_tunel_2.jpg", size: "3.7 MB", at: daysAgo(5, 11, 38) },
    ],
    timeline: [
      ev("creado", 5, "Carlos Eduardo Flores", "reportante", "Reporte de inspección de túnel"),
      ev("aprobado", 4, "M. Falcón", "seguridad", "Caso aprobado por Seguridad Operativa"),
      ev("derivado", 4, "M. Falcón", "seguridad", `Derivado a ${AREA_HEADS.infraestructura} · ${AREA_LABELS.infraestructura}`),
      ev("investigacion", 2, AREA_HEADS.infraestructura, "reportante", "Hallazgos registrados"),
      ev("plan_propuesto", 1, AREA_HEADS.infraestructura, "reportante", "Plan de acción propuesto", "Reparación de tubería y sellado de filtración."),
    ],
    investigation: {
      technicalDescription: "Túnel de concreto armado, sección 5.2m. Pared norte con filtración activa.",
      findings: "Tubería PVC de drenaje de 150mm con ruptura en unión. Agua de lluvia infiltrando por grieta en pavimento.",
      rootCause: "Deterioro de unión por envejecimiento de material + carga vehicular excesiva en superficie.",
      conclusions: "Requiere reparación de tubería y refuerzo de pavimento. Monitoreo continuo por 30 días.",
      observations: "Coordinar con municipalidad para restricción de carga en zona afectada.",
      updatedAt: daysAgo(2, 10, 0),
    },
    actionPlans: [
      {
        elaboratedBy: "Marcela Falcón",
        actionType: "Correctiva",
        description: "Reparación de tubería de drenaje y sellado de filtración en túnel.",
        startDate: daysAgo(2).slice(0, 10),
        dueDate: daysAhead(10),
        estimatedTime: "10 días",
        priority: "alta" as Priority,
        observations: "Requiere trabajo nocturno para no afectar servicio.",
        sentToArea: "mantenimiento",
        items: [
          {
            id: uid("ai"),
            name: "Localización exacta de ruptura en tubería",
            description: "Usar cámara de inspección para localizar punto exacto de ruptura",
            owner: AREA_HEADS.ingenieria,
            priority: "alta" as Priority,
            startDate: daysAgo(2).slice(0, 10),
            dueDate: daysAhead(1),
            progress: 100,
            status: "completado",
            comments: [{ id: uid("comment"), text: "Ruptura localizada a 147m de Angamos.", author: AREA_HEADS.mr, at: daysAgo(1) }],
          },
          {
            id: uid("ai"),
            name: "Excavación y exposición de tubería",
            description: "Excavación controlada para excluir tubería dañada",
            owner: AREA_HEADS.ingenieria,
            priority: "alta" as Priority,
            startDate: daysAgo(1).slice(0, 10),
            dueDate: daysAhead(3),
            progress: 0,
            status: "pendiente",
            comments: [],
          },
          {
            id: uid("ai"),
            name: "Reemplazo de sección de tubería",
            description: "Reemplazar 3m de tubería PVC dañada",
            owner: AREA_HEADS.ingenieria,
            priority: "alta" as Priority,
            startDate: daysAhead(3),
            dueDate: daysAhead(5),
            progress: 0,
            status: "pendiente",
            comments: [],
          },
          {
            id: uid("ai"),
            name: "Sellado de filtración en túnel",
            description: "Aplicar sellante epóxico en pared del túnel",
            owner: AREA_HEADS.ingenieria,
            priority: "alta" as Priority,
            startDate: daysAhead(5),
            dueDate: daysAhead(7),
            progress: 0,
            status: "pendiente",
            comments: [],
          },
          {
            id: uid("ai"),
            name: "Recompactación y restauración",
            description: "Rellenar excavación y restaurar pavimento",
            owner: AREA_HEADS.ingenieria,
            priority: "media" as Priority,
            startDate: daysAhead(7),
            dueDate: daysAhead(10),
            progress: 0,
            status: "pendiente",
            comments: [],
          },
        ],
        submittedAt: daysAgo(1, 16, 0),
      },
    ],
    slaDueDate: daysAhead(7),
    createdAt: daysAgo(5),
  },
  {
    id: "SOP-14-2026",
    type: "accidente",
    title: "Caída de personal en plataforma de estación Cabitos",
    description:
      "Durante tareas de inspección en la plataforma sur, un técnico resbaló sobre superficie mojada y sufrió luxación de muñeca. Se activó protocolo de primeros auxilios y traslado a centro asistencial.",
    observations:
      "El área presentaba humedad por condensación. Señalización temporal se encontraba fuera de posición.",
    area: "mantenimiento",
    station: "Cabitos",
    location: "Plataforma sur · vía 2",
    date: daysAgo(2, 7, 35).slice(0, 10),
    time: "07:35",
    priority: "critica",
    riskLevel: "1A",
    stage: "investigacion",
    reporter: "Carlos Núñez",
    reporterRole: "reportante",
    assignee: AREA_HEADS.mantenimiento,
    assigneeArea: "mantenimiento",
    evidence: [
      { id: uid("ev"), kind: "foto", name: "plataforma_sur_1.jpg", size: "2.4 MB", at: daysAgo(2, 7, 40) },
      { id: uid("ev"), kind: "foto", name: "plataforma_sur_2.jpg", size: "3.1 MB", at: daysAgo(2, 7, 42) },
      { id: uid("ev"), kind: "documento", name: "parte_medico.pdf", size: "612 KB", at: daysAgo(1, 10, 5) },
    ],
    timeline: [
      ev("creado", 2, "Carlos Núñez", "reportante", "Reporte registrado por trabajador"),
      ev("aprobado", 1, "M. Falcón", "seguridad", "Caso aprobado por Seguridad Operativa"),
      ev("derivado", 1, "M. Falcón", "seguridad", `Derivado a ${AREA_HEADS.mantenimiento} · ${AREA_LABELS.mantenimiento}`, "Correo enviado al jefe de área. Inicia investigación."),
    ],
    sop: {
      fechaHallazgo: daysAgo(2).slice(0, 10),
      fechaEvento: daysAgo(2, 7, 35),
      estadoHallazgo: "en_proceso",
      procedencia: "incidencias",
      tipoHallazgo: "no_conformidad",
      responsableInvestigacion: "Antonio Rebaza Lizaraso",
      tipoSOP: "accidente",
      subtipoSOP: "caida",
      peligro: "Superficie mojada sin señalización",
      consecuencia: "Luxación de muñeca en técnico de mantenimiento",
      analisisRiesgo: "1A",
      acr: "ACC-001",
      planCodigo: "SOP-14-2026-PLA-01",
      planDescripcion: "Instalar señalización permanente y mejorar drenaje en plataforma sur.",
      planArea: "mantenimiento",
      planResponsable: "Alejandro Vielma",
      planEstado: "pendiente",
      planFecha: daysAgo(1).slice(0, 10),
      planFechaProgramada: daysAhead(7).slice(0, 10),
    },
    evento: {
      rangoHorario: "06:00 - 07:59",
      tipoIncidenteOperativo: "caida_estacion",
      descripcionEvento: "Técnico resbala en plataforma sur por superficie mojada.",
      ubicacion: "estacion",
      tipoVia: "par",
      lugarIncidente: "CAB",
      modeloMR: "N/A",
      nroMR: "N/A",
      personalFalla: "tecnico",
      tipoCausa: "falla_operacional",
      posibleCausa: "Distracción",
      informacionAdicional: "Superficie sin señalización de peligro.",
    },
    slaDueDate: daysAhead(6),
    createdAt: daysAgo(2),
  },
  {
    id: "SOP-13-2026",
    type: "falla_operativa",
    title: "Falla intermitente en señalamiento tramo Atocongo–Pamplona",
    description:
      "Señales de tránsito ferroviario presentan corte intermitente entre Atocongo y Pamplona durante horas punta. Se reportan tres eventos de frenado de emergencia en la semana.",
    observations: "Patrón se repite entre 07:30–08:15 y 18:00–18:45.",
    area: "ingenieria",
    station: "Atocongo",
    location: "Tramo Atocongo ↔ Pamplona · vía 1",
    date: daysAgo(4, 8, 10).slice(0, 10),
    time: "08:10",
    priority: "alta",
        riskLevel: "2C",
    stage: "investigacion",
    reporter: "Lucía Ramírez",
    reporterRole: "reportante",
    assignee: AREA_HEADS.ingenieria,
    assigneeArea: "ingenieria",
    evidence: [
      { id: uid("ev"), kind: "video", name: "falla_señal.mp4", size: "18.7 MB", at: daysAgo(4, 8, 14) },
      { id: uid("ev"), kind: "documento", name: "log_operacion.xlsx", size: "244 KB", at: daysAgo(3, 9, 30) },
    ],
    timeline: [
      ev("creado", 4, "Lucía Ramírez", "reportante", "Reporte registrado por trabajador"),
      ev("aprobado", 3, "M. Falcón", "seguridad", "Caso aprobado por Seguridad Operativa"),
      ev("derivado", 3, "M. Falcón", "seguridad", `Derivado a ${AREA_HEADS.ingenieria} · ${AREA_LABELS.ingenieria}`),
      ev("investigacion", 1, AREA_HEADS.ingenieria, "reportante", "Investigación iniciada", "Inspección de gabinetes y revisión de históricos de tensión."),
    ],
    investigation: {
      technicalDescription: "—", findings:
        "Fluctuación de tensión en subestación ATO-03 fuera de rango nominal. Gabinete de control con humedad interna.",
      rootCause:
        "Envejecimiento de aislamiento en transformador de medición + sello de gabinete deteriorado.",
      conclusions:
        "Falla atribuible a degradación de infraestructura eléctrica. Requiere reemplazo programado.",
      observations: "Recomendable programar mantenimiento preventivo en tramos adyacentes.",
      updatedAt: daysAgo(1, 11, 0),
    },
    slaDueDate: daysAhead(3),
    createdAt: daysAgo(4),
  },
  {
    id: "SOP-12-2026",
    type: "condicion_insegura",
    title: "Baranda perimetral suelta en andén estación La Cultura",
    description:
      "Tramo de baranda metálica perimetral presenta holgura y un tornillo faltante. Riesgo de caída al carril para personal de mantenimiento durante horas no operativas.",
    observations: "Ubicada cerca de acceso técnico sur.",
    area: "infraestructura",
    station: "La Cultura",
    location: "Andén central · extremo sur",
    date: daysAgo(6, 14, 20).slice(0, 10),
    time: "14:20",
    priority: "media",
        riskLevel: "3C",
    stage: "plan_accion",
    reporter: "Fernando Quispe",
    reporterRole: "reportante",
    assignee: AREA_HEADS.infraestructura,
    assigneeArea: "infraestructura",
    evidence: [
      { id: uid("ev"), kind: "foto", name: "baranda_suelta.jpg", size: "1.8 MB", at: daysAgo(6, 14, 25) },
    ],
    timeline: [
      ev("creado", 6, "Fernando Quispe", "reportante", "Reporte registrado por trabajador"),
      ev("aprobado", 5, "M. Falcón", "seguridad", "Caso aprobado por Seguridad Operativa"),
      ev("derivado", 5, "M. Falcón", "seguridad", `Derivado a ${AREA_HEADS.infraestructura} · ${AREA_LABELS.infraestructura}`),
      ev("investigacion", 3, AREA_HEADS.infraestructura, "reportante", "Hallazgos de investigación registrados"),
      ev("plan_propuesto", 1, AREA_HEADS.infraestructura, "reportante", "Plan de acción propuesto", "3 acciones correctivas, plazo 7 días."),
    ],
    investigation: {
      technicalDescription: "—", findings:
        "Tres tornillos de anclaje con corrosión avanzada. Baranda requiere reapriete y reemplazo de elementos.",
      rootCause: "Corrosión por humedad ambiente + falta de mantenimiento preventivo programado.",
      conclusions: "Condición aislada pero repetible en estaciones de similar antigüedad.",
      observations: "Sugerir inspección integral en estaciones Javier Prado, Cabitos y Ayacucho.",
      updatedAt: daysAgo(3, 10, 0),
    },
    actionPlans: [
      { elaboratedBy: "Marcela Falcón", actionType: "Correctiva", description: "Plan de acción correctivo derivado de la investigación.", startDate: daysAgo(3).slice(0, 10), dueDate: daysAhead(7), estimatedTime: "7 días", priority: "media" as Priority, observations: "Coordinar con el jefe del área responsable.", sentToArea: "mantenimiento", items: [
        { id: uid("ai"), name: "Reapriete y reemplazo de tornillería en baranda afectada", description: "Reapriete y reemplazo de tornillería en baranda afectada", owner: AREA_HEADS.infraestructura, priority: "media" as Priority, startDate: daysAgo(3).slice(0, 10), dueDate: daysAhead(2), progress: 0, status: "pendiente", comments: [] as ActivityComment[] },
        { id: uid("ai"), name: "Inspección de barandas en estaciones similares", description: "Inspección de barandas en estaciones similares", owner: AREA_HEADS.infraestructura, priority: "media" as Priority, startDate: daysAgo(3).slice(0, 10), dueDate: daysAhead(5), progress: 0, status: "pendiente", comments: [] as ActivityComment[] },
        { id: uid("ai"), name: "Inclusión en plan preventivo trimestral", description: "Inclusión en plan preventivo trimestral", owner: AREA_HEADS.infraestructura, priority: "media" as Priority, startDate: daysAgo(3).slice(0, 10), dueDate: daysAhead(7), progress: 0, status: "pendiente", comments: [] as ActivityComment[] },
      ],
      submittedAt: daysAgo(1, 16, 30),
    },
    ],
    slaDueDate: daysAhead(4),
    createdAt: daysAgo(6),
  },
  {
    id: "SOP-11-2026",
    type: "acto_inseguro",
    title: "Personal sin EPP en zona de vías — San Juan",
    description:
      "Operario observado sin casco y sin chaleco reflectivo en zona de vías durante jornada de mantenimiento nocturno.",
    observations: "Observación reportada por supervisor de turno.",
    area: "mantenimiento",
    station: "San Juan",
    location: "Zona de vías · acceso norte",
    date: daysAgo(8, 22, 45).slice(0, 10),
    time: "22:45",
    priority: "alta",
    riskLevel: "2C",
    stage: "ejecucion",
    reporter: "Sofía Erazo",
    reporterRole: "reportante",
    assignee: AREA_HEADS.mantenimiento,
    assigneeArea: "operaciones",
    evidence: [
      { id: uid("ev"), kind: "foto", name: "observacion_epp.jpg", size: "1.2 MB", at: daysAgo(8, 22, 50) },
    ],
    timeline: [
      ev("creado", 8, "Sofía Erazo", "reportante", "Observación registrada"),
      ev("aprobado", 7, "M. Falcón", "seguridad", "Caso aprobado por Seguridad Operativa"),
      ev("derivado", 7, "M. Falcón", "seguridad", `Derivado a ${AREA_HEADS.operaciones} · ${AREA_LABELS.operaciones}`),
      ev("investigacion", 5, AREA_HEADS.operaciones, "reportante", "Investigación registrada"),
      ev("plan_propuesto", 4, AREA_HEADS.operaciones, "reportante", "Plan de acción propuesto"),
      ev("plan_aprobado", 3, "M. Falcón", "seguridad", "Plan aprobado por Seguridad Operativa"),
      ev("ejecucion", 1, AREA_HEADS.operaciones, "reportante", "Avance 60% registrado", "Capacitación EPP realizada al 80% del personal."),
    ],
    investigation: {
      technicalDescription: "—", findings: "Personal nuevo sin inducción completa. Supervisor no verificó EPP al ingreso.",
      rootCause: "Proceso de inducción incompleto + falta de verificación en acceso.",
      conclusions: "Reforzar control de EPP en accesos y completar inducción de personal nuevo.",
      observations: "Coordinar con RR.HH. el padrón actualizado de personal nuevo.",
      updatedAt: daysAgo(5, 10, 0),
    },
    actionPlans: [
      { elaboratedBy: "Marcela Falcón", actionType: "Correctiva", description: "Plan de acción correctivo derivado de la investigación.", startDate: daysAgo(3).slice(0, 10), dueDate: daysAhead(7), estimatedTime: "7 días", priority: "media" as Priority, observations: "Coordinar con el jefe del área responsable.", sentToArea: "mantenimiento", items: [
        { id: uid("ai"), name: "Completar inducción de seguridad al personal nuevo", description: "Completar inducción de seguridad al personal nuevo", owner: AREA_HEADS.mantenimiento, priority: "media" as Priority, startDate: daysAgo(3).slice(0, 10), dueDate: daysAhead(-1), progress: 80, status: "en_progreso", comments: [] as ActivityComment[] },
        { id: uid("ai"), name: "Implementar checklist EPP en puntos de acceso", description: "Implementar checklist EPP en puntos de acceso", owner: AREA_HEADS.mantenimiento, priority: "media" as Priority, startDate: daysAgo(3).slice(0, 10), dueDate: daysAhead(1), progress: 60, status: "en_progreso", comments: [] as ActivityComment[] },
        { id: uid("ai"), name: "Charla de concientización al turno nocturno", description: "Charla de concientización al turno nocturno", owner: AREA_HEADS.mantenimiento, priority: "media" as Priority, startDate: daysAgo(3).slice(0, 10), dueDate: daysAhead(3), progress: 40, status: "en_progreso", comments: [] as ActivityComment[] },
      ],
      submittedAt: daysAgo(4, 15, 0),
      reviewedAt: daysAgo(3, 9, 30),
      reviewDecision: "aprobado",
    },
    ],
    execution: {
      progress: 60,
      updates: [
        { id: uid("ex"), at: daysAgo(3, 17, 0), author: AREA_HEADS.operaciones, progress: 20, comment: "Inicio de capacitación al turno nocturno." },
        { id: uid("ex"), at: daysAgo(2, 11, 0), author: AREA_HEADS.operaciones, progress: 40, comment: "Checklist implementado en 3 de 5 accesos." },
        { id: uid("ex"), at: daysAgo(1, 18, 0), author: AREA_HEADS.operaciones, progress: 60, comment: "Capacitación al 80% del personal. Faltan dos grupos." },
      ],
    },
    slaDueDate: daysAhead(5),
    createdAt: daysAgo(8),
  },
  {
    id: "SOP-10-2026",
    type: "observacion",
    title: "Iluminación deficiente en paso peatonal — Bayovar",
    description:
      "Pasillo de acceso peatonal presenta dos luminarias apagadas. Condiciones de visibilidad reducidas en horas de cierre.",
    observations: "Reportado por personal de limpieza.",
    area: "mantenimiento",
    station: "Bayovar",
    location: "Acceso peatonal · nivel -1",
    date: daysAgo(10, 19, 15).slice(0, 10),
    time: "19:15",
    priority: "baja",
        riskLevel: "4C",
    stage: "verificacion",
    reporter: "Mario Chávez",
    reporterRole: "reportante",
    assignee: AREA_HEADS.mantenimiento,
    assigneeArea: "mantenimiento",
    evidence: [
      { id: uid("ev"), kind: "foto", name: "iluminacion.jpg", size: "1.4 MB", at: daysAgo(10, 19, 18) },
    ],
    timeline: [
      ev("creado", 10, "Mario Chávez", "reportante", "Observación registrada"),
      ev("aprobado", 9, "M. Falcón", "seguridad", "Caso aprobado por Seguridad Operativa"),
      ev("derivado", 9, "M. Falcón", "seguridad", `Derivado a ${AREA_HEADS.mantenimiento} · ${AREA_LABELS.mantenimiento}`),
      ev("investigacion", 7, AREA_HEADS.mantenimiento, "reportante", "Investigación registrada"),
      ev("plan_propuesto", 6, AREA_HEADS.mantenimiento, "reportante", "Plan propuesto"),
      ev("plan_aprobado", 5, "M. Falcón", "seguridad", "Plan aprobado"),
      ev("ejecucion", 3, AREA_HEADS.mantenimiento, "reportante", "Avance 90%", "Luminarias reemplazadas. Prueba de funcionamiento pendiente."),
      ev("seguimiento", 1, "M. Falcón", "seguridad", "Seguimiento de cierre", "Verificar funcionamiento en horario nocturno."),
    ],
    investigation: {
      technicalDescription: "—", findings: "Dos luminarias LED con fuente de alimentación dañada por variación de tensión.",
      rootCause: "Falta de regulador de tensión en circuito del pasillo.",
      conclusions: "Reemplazo de luminarias + instalación de regulador recomendada.",
      observations: "Extender revisión a circuitos de pasillos adyacentes.",
      updatedAt: daysAgo(7, 10, 0),
    },
    actionPlans: [
      { elaboratedBy: "Marcela Falcón", actionType: "Correctiva", description: "Plan de acción correctivo derivado de la investigación.", startDate: daysAgo(3).slice(0, 10), dueDate: daysAhead(7), estimatedTime: "7 días", priority: "media" as Priority, observations: "Coordinar con el jefe del área responsable.", sentToArea: "mantenimiento", items: [
        { id: uid("ai"), name: "Reemplazo de luminarias LED", description: "Reemplazo de luminarias LED", owner: AREA_HEADS.mantenimiento, priority: "media" as Priority, startDate: daysAgo(3).slice(0, 10), dueDate: daysAhead(-2), progress: 100, status: "completado", comments: [] as ActivityComment[] },
        { id: uid("ai"), name: "Instalación de regulador de tensión", description: "Instalación de regulador de tensión", owner: AREA_HEADS.mantenimiento, priority: "media" as Priority, startDate: daysAgo(3).slice(0, 10), dueDate: daysAhead(0), progress: 90, status: "en_progreso", comments: [] as ActivityComment[] },
        { id: uid("ai"), name: "Prueba de funcionamiento nocturno", description: "Prueba de funcionamiento nocturno", owner: AREA_HEADS.mantenimiento, priority: "media" as Priority, startDate: daysAgo(3).slice(0, 10), dueDate: daysAhead(1), progress: 0, status: "pendiente", comments: [] as ActivityComment[] },
      ],
      submittedAt: daysAgo(6, 15, 0),
      reviewedAt: daysAgo(5, 9, 30),
      reviewDecision: "aprobado",
    },
    ],
    execution: {
      progress: 90,
      updates: [
        { id: uid("ex"), at: daysAgo(5, 16, 0), author: AREA_HEADS.mantenimiento, progress: 30, comment: "Luminarias retiradas." },
        { id: uid("ex"), at: daysAgo(3, 14, 0), author: AREA_HEADS.mantenimiento, progress: 80, comment: "Luminarias reemplazadas. Regulador en curso." },
        { id: uid("ex"), at: daysAgo(1, 17, 0), author: AREA_HEADS.mantenimiento, progress: 90, comment: "Regulador instalado. Prueba nocturna pendiente." },
      ],
    },
    slaDueDate: daysAhead(1),
    createdAt: daysAgo(10),
  },
  {
    id: "SOP-09-2026",
    type: "incidente",
    title: "Puerta de andén con cierre defectuoso — Pamplona",
    description:
      "Puerta de andén no completa ciclo de cierre, permanece entreabierta generando riesgo de acceso a vía.",
    observations: "Falla reportada en dos oportunidades durante la semana.",
    area: "material_rodante",
    station: "Villa Maria",
    location: "Andén · puerta 3",
    date: daysAgo(12, 11, 5).slice(0, 10),
    time: "11:05",
    priority: "alta",
        riskLevel: "2C",
    stage: "cierre",
    reporter: "Diego Salas",
    reporterRole: "reportante",
    assignee: AREA_HEADS.material_rodante,
    assigneeArea: "material_rodante",
    evidence: [
      { id: uid("ev"), kind: "foto", name: "puerta_anden.jpg", size: "2.0 MB", at: daysAgo(12, 11, 10) },
      { id: uid("ev"), kind: "documento", name: "reporte_tecnico.pdf", size: "880 KB", at: daysAgo(9, 10, 0) },
    ],
    timeline: [
      ev("creado", 12, "Diego Salas", "reportante", "Incidente registrado"),
      ev("aprobado", 11, "M. Falcón", "seguridad", "Caso aprobado por Seguridad Operativa"),
      ev("derivado", 11, "M. Falcón", "seguridad", `Derivado a ${AREA_HEADS.material_rodante} · ${AREA_LABELS.material_rodante}`),
      ev("investigacion", 9, AREA_HEADS.material_rodante, "reportante", "Investigación registrada"),
      ev("plan_propuesto", 8, AREA_HEADS.material_rodante, "reportante", "Plan propuesto"),
      ev("plan_aprobado", 7, "M. Falcón", "seguridad", "Plan aprobado"),
      ev("ejecucion", 4, AREA_HEADS.material_rodante, "reportante", "Avance 100%", "Actuador reemplazado y prueba de ciclo correcta."),
      ev("seguimiento", 2, "M. Falcón", "seguridad", "Verificación final OK"),
      ev("cierre", 1, "M. Falcón", "seguridad", "Caso cerrado", "Historial completo generado y archivado."),
    ],
    investigation: {
      technicalDescription: "—", findings: "Actuador neumático con fuga de sello. Ciclo incompleto por presión insuficiente.",
      rootCause: "Desgaste de sello por uso prolongado sin mantenimiento preventivo.",
      conclusions: "Reemplazo de actuador + ajuste de presión. Reprogramar mantenimiento.",
      observations: "Recomendable revisar puertas gemelas en estaciones Pamplona y Matellini.",
      updatedAt: daysAgo(9, 10, 0),
    },
    actionPlans: [
      { elaboratedBy: "Marcela Falcón", actionType: "Correctiva", description: "Plan de acción correctivo derivado de la investigación.", startDate: daysAgo(3).slice(0, 10), dueDate: daysAhead(7), estimatedTime: "7 días", priority: "media" as Priority, observations: "Coordinar con el jefe del área responsable.", sentToArea: "mantenimiento", items: [
        { id: uid("ai"), name: "Reemplazo de actuador neumático", description: "Reemplazo de actuador neumático", owner: AREA_HEADS.material_rodante, priority: "media" as Priority, startDate: daysAgo(3).slice(0, 10), dueDate: daysAhead(-5), progress: 100, status: "completado", comments: [] as ActivityComment[] },
        { id: uid("ai"), name: "Ajuste de presión del sistema", description: "Ajuste de presión del sistema", owner: AREA_HEADS.material_rodante, priority: "media" as Priority, startDate: daysAgo(3).slice(0, 10), dueDate: daysAhead(-4), progress: 100, status: "completado", comments: [] as ActivityComment[] },
        { id: uid("ai"), name: "Revisión de puertas gemelas", description: "Revisión de puertas gemelas", owner: AREA_HEADS.material_rodante, priority: "media" as Priority, startDate: daysAgo(3).slice(0, 10), dueDate: daysAhead(-2), progress: 100, status: "completado", comments: [] as ActivityComment[] },
      ],
      submittedAt: daysAgo(8, 15, 0),
      reviewedAt: daysAgo(7, 9, 30),
      reviewDecision: "aprobado",
    },
    ],
    execution: {
      progress: 100,
      updates: [
        { id: uid("ex"), at: daysAgo(6, 16, 0), author: AREA_HEADS.material_rodante, progress: 40, comment: "Actuador retirado." },
        { id: uid("ex"), at: daysAgo(5, 11, 0), author: AREA_HEADS.material_rodante, progress: 80, comment: "Actuador reemplazado y presión ajustada." },
        { id: uid("ex"), at: daysAgo(4, 17, 0), author: AREA_HEADS.material_rodante, progress: 100, comment: "Prueba de ciclo correcta. Puerta operativa." },
      ],
    },
    slaDueDate: daysAgo(1),
    createdAt: daysAgo(12),
    closedAt: daysAgo(1, 16, 0),
  },
  {
    id: "SOP-08-2026",
    type: "riesgo",
    title: "Sobrecarga eléctrica en tablero de subestación Maria Auxiliadora",
    description:
      "Tablero de distribución presenta temperatura elevada y olor a quemado. Riesgo de falla mayor y posible incendio eléctrico.",
    observations: "Detectado durante inspección rutinaria.",
    area: "ingenieria",
    station: "Maria Auxiliadora",
    location: "Sala de tableros · nivel -2",
    date: daysAgo(2, 9, 30).slice(0, 10),
    time: "09:30",
    priority: "critica",
    riskLevel: "1A",
    stage: "verificacion",
    reporter: "Roberto Gutiérrez",
    reporterRole: "reportante",
    assignee: AREA_HEADS.ingenieria,
    assigneeArea: "ingenieria",
    evidence: [
      { id: uid("ev"), kind: "foto", name: "tablero_caliente.jpg", size: "2.5 MB", at: daysAgo(2, 9, 35) },
      { id: uid("ev"), kind: "documento", name: "reporte_termico.pdf", size: "1.2 MB", at: daysAgo(2, 10, 0) },
    ],
    timeline: [
      ev("creado", 2, "Roberto Gutiérrez", "reportante", "Reporte de inspección rutinaria"),
      ev("aprobado", 1, "M. Falcón", "seguridad", "Caso aprobado por Seguridad Operativa"),
      ev("derivado", 1, "M. Falcón", "seguridad", `Derivado a ${AREA_HEADS.ingenieria} · ${AREA_LABELS.ingenieria}`),
      ev("investigacion", 0, AREA_HEADS.ingenieria, "reportante", "Investigación completada"),
      ev("plan_propuesto", 0, AREA_HEADS.ingenieria, "reportante", "Plan de acción propuesto"),
      ev("plan_aprobado", 0, "M. Falcón", "seguridad", "Plan aprobado por Seguridad Operativa"),
      ev("ejecucion", 0, AREA_HEADS.ingenieria, "reportante", "Ejecución iniciada"),
      ev("ampliacion", 0, AREA_HEADS.ingenieria, "reportante", "Solicitud de ampliación de plazo enviada", "Se requiere más tiempo para adquisición de componentes"),
    ],
    investigation: {
      technicalDescription: "Tablero de distribución Schneider Electric, modelo 2017. Sobrecarga en fase L2.",
      findings: "Termómetro marca 85°C en fase L2. Olor a quemado indica posible daño aislamiento.",
      rootCause: "Carga excesiva en fase L2 por conexión temporal de equipos de prueba sin redistribución.",
      conclusions: "Requiere redistribución de carga y verificación de aislamiento. Monitoreo continuo por 48 horas.",
      observations: "Coordinar con Operaciones para redistribución de carga temporal.",
      updatedAt: daysAgo(1, 14, 0),
    },
    actionPlans: [
      {
        elaboratedBy: "Marcela Falcón",
        actionType: "Correctiva",
        description: "Redistribución de carga y verificación de aislamiento en tablero.",
        startDate: daysAgo(1).slice(0, 10),
        dueDate: daysAhead(2),
        estimatedTime: "3 días",
        priority: "critica" as Priority,
        observations: "Requiere coordinación con Operaciones para redistribución de carga.",
        sentToArea: "ingenieria",
        items: [
          { id: uid("ai"), name: "Redistribución de carga en fase L2", description: "Redistribuir carga para aliviar fase L2", owner: AREA_HEADS.ingenieria, priority: "critica" as Priority, startDate: daysAgo(1).slice(0, 10), dueDate: daysAhead(1), progress: 100, status: "completado", comments: [{ id: uid("comment"), text: "Carga redistribuida correctamente", author: AREA_HEADS.ingenieria, at: daysAgo(1) }] },
          { id: uid("ai"), name: "Verificación de aislamiento", description: "Verificar estado de aislamiento en fase L2", owner: AREA_HEADS.ingenieria, priority: "critica" as Priority, startDate: daysAgo(1).slice(0, 10), dueDate: daysAhead(2), progress: 50, status: "en_progreso", comments: [{ id: uid("comment"), text: "Pruebas en progreso", author: AREA_HEADS.ingenieria, at: daysAgo(1) }] },
        ],
        submittedAt: daysAgo(1, 16, 0),
        reviewedAt: daysAgo(1, 9, 30),
        reviewDecision: "aprobado",
      },
    ],
    execution: {
      progress: 50,
      acceptedByAreaAt: daysAgo(1, 10, 0),
      updates: [
        { id: uid("ex"), at: daysAgo(1, 17, 0), author: AREA_HEADS.ingenieria, progress: 50, comment: "Carga redistribuida. Inicio verificación de aislamiento." },
      ],
    },
    extensionRequest: {
      motivo: "Componentes de aislamiento especializados no disponibles en stock local. Requiere importación desde Chile.",
      nuevaFecha: daysAhead(7),
      justificacion: "Proveedor local no tiene stock. Tiempo de importación estimado: 5 días hábiles.",
      requestedAt: new Date().toISOString(),
    },
    slaDueDate: daysAhead(2),
    createdAt: daysAgo(2),
  },
  {
    id: "SOP-07-2026",
    type: "hallazgo",
    title: "Documentación de procedimiento desactualizada — Comunicaciones",
    description:
      "Procedimiento de respuesta a falla de radiocomunicación data de 2022. No incluye canales digitales actuales.",
    observations: "Hallazgo de auditoría interna.",
    area: "comunicaciones",
    station: "Bayovar",
    location: "Operaciones · centro de control",
    date: daysAgo(3, 10, 30).slice(0, 10),
    time: "10:30",
    priority: "media",
        riskLevel: "3C",
    stage: "evaluacion",
    reporter: "M. Falcón",
    reporterRole: "seguridad",
    evidence: [
      { id: uid("ev"), kind: "documento", name: "procedimiento_2022.pdf", size: "1.2 MB", at: daysAgo(3, 10, 35) },
    ],
    timeline: [
      ev("creado", 3, "M. Falcón", "seguridad", "Hallazgo de auditoría registrado"),
    ],
    slaDueDate: daysAhead(7),
    createdAt: daysAgo(3),
  },
  {
    id: "SOP-06-2026",
    type: "incumplimiento",
    title: "Incumplimiento de protocolo de bloqueo y etiquetado (LOTO)",
    description:
      "Personal de contratista ejecutó trabajos sin aplicar protocolo LTO en tablero de Subestación Puno.",
    observations: "Detectado por supervisor de turno.",
    area: "ingenieria",
    station: "Pumacahua",
    location: "Subestación · sala de tableros",
    date: daysAgo(5, 13, 40).slice(0, 10),
    time: "13:40",
    priority: "critica",
        riskLevel: "1A",
    stage: "pendiente_info",
    reporter: "Hugo Reyna",
    reporterRole: "reportante",
    evidence: [
      { id: uid("ev"), kind: "documento", name: "registro_contratista.pdf", size: "540 KB", at: daysAgo(5, 13, 45) },
    ],
    timeline: [
      ev("creado", 5, "Hugo Reyna", "reportante", "Incumplimiento registrado"),
      ev("info_solicitada", 2, "M. Falcón", "seguridad", "Información solicitada al reportante", "Se requiere detallar personal involucrado y copia del permiso de trabajo."),
    ],
    pendingInfoRequest: {
      question:
        "Detallar personal de contratista involucrado y adjuntar copia del permiso de trabajo firmado.",
      requestedAt: daysAgo(2, 9, 15),
    },
    slaDueDate: daysAhead(1),
    createdAt: daysAgo(5),
  },
  {
    id: "SOP-15-2026",
    type: "falla_operativa",
    title: "Falla en sistema de ventilación de túnel — tramo Cabitos",
    description:
      "El sistema de ventilación del túnel entre Cabitos y Ayacucho presenta fallas intermitentes. Se detectó sobrecalentamiento en motor de extracción 2 durante inspección rutinaria.",
    observations: "Requiere atención inmediata para evitar suspensión del servicio.",
    area: "mantenimiento",
    station: "Cabitos",
    location: "Túnel · tramo Cabitos–Ayacucho",
    date: daysAgo(6, 6, 30).slice(0, 10),
    time: "06:30",
    priority: "alta",
    riskLevel: "2C",
    stage: "ejecucion",
    reporter: "Lucía Ramírez",
    reporterRole: "reportante",
    assignee: AREA_HEADS.mantenimiento,
    assigneeArea: "mantenimiento",
    evidence: [
      { id: uid("ev"), kind: "foto", name: "ventilador_falla.jpg", size: "2.8 MB", at: daysAgo(6, 6, 35) },
      { id: uid("ev"), kind: "documento", name: "informe_inspeccion.pdf", size: "1.2 MB", at: daysAgo(5, 10, 0) },
    ],
    timeline: [
      ev("creado", 6, "Lucía Ramírez", "reportante", "Reporte registrado"),
      ev("aprobado", 5, "M. Falcón", "seguridad", "Reporte aprobado"),
      ev("investigacion", 4, "M. Falcón", "seguridad", "Investigación registrada", "Sobrecarga por falta de mantenimiento preventivo."),
      ev("plan_propuesto", 3, "M. Falcón", "seguridad", `Plan enviado a ${AREA_HEADS.mantenimiento} · Mantenimiento`),
      ev("plan_aprobado", 2, "M. Falcón", "seguridad", "Plan aprobado — ejecución iniciada"),
      ev("plan_aprobado", 2, AREA_HEADS.mantenimiento, "reportante", "Plan aceptado por el jefe del área"),
    ],
    investigation: {
      findings: "Motor de extracción 2 con bobinado degradado y filtro de aire obstruido.",
      rootCause: "Falta de mantenimiento preventivo programado en ciclo trimestral.",
      technicalDescription: "Corriente de arranque 18% sobre nominal. Temperatura de operación 78°C (límite 65°C). Aislamiento clase F degradado.",
      conclusions: "Requiere reemplazo de motor y limpieza de filtros. Reprogramar mantenimiento preventivo.",
      observations: "Extender revisión a los 4 extractores del tramo.",
      updatedAt: daysAgo(4, 10, 0),
    },
    actionPlans: [
      {
        elaboratedBy: "Marcela Falcón",
        actionType: "Correctiva",
        description: "Reemplazo del motor de extracción 2 y limpieza de filtros en tramo Cabitos–Ayacucho. Reprogramación del mantenimiento preventivo trimestral.",
        startDate: daysAgo(2).slice(0, 10),
        dueDate: daysAhead(5),
        estimatedTime: "7 días",
        priority: "alta" as Priority,
        observations: "Coordinar con Operaciones para ventanas de mantenimiento nocturno (00:00–04:00).",
        sentToArea: "mantenimiento",
        items: [
          { id: uid("ai"), name: "Adquisición de motor de extracción de reemplazo", description: "Solicitar y adquirir motor equivalente al modelo instalado.", owner: AREA_HEADS.mantenimiento, priority: "alta" as Priority, startDate: daysAgo(2).slice(0, 10), dueDate: daysAhead(1), progress: 100, status: "completado", comments: [{ id: uid("comment"), text: "Motor adquirido y recibido en almacén.", author: AREA_HEADS.mantenimiento, at: daysAgo(1) }] },
          { id: uid("ai"), name: "Limpieza de filtros de extracción", description: "Desmontaje y limpieza de los 4 filtros del tramo.", owner: AREA_HEADS.mantenimiento, priority: "media" as Priority, startDate: daysAgo(1).slice(0, 10), dueDate: daysAhead(2), progress: 50, status: "en_progreso", comments: [{ id: uid("comment"), text: "2 de 4 filtros limpiados.", author: AREA_HEADS.mantenimiento, at: daysAgo(1) }] },
          { id: uid("ai"), name: "Reemplazo del motor de extracción 2", description: "Desmontaje del motor fallado e instalación del nuevo.", owner: AREA_HEADS.mantenimiento, priority: "alta" as Priority, startDate: daysAhead(1), dueDate: daysAhead(3), progress: 0, status: "pendiente", comments: [] },
          { id: uid("ai"), name: "Prueba de funcionamiento y puesta en marcha", description: "Pruebas de corriente, temperatura y operación continua 24h.", owner: AREA_HEADS.mantenimiento, priority: "alta" as Priority, startDate: daysAhead(3), dueDate: daysAhead(5), progress: 0, status: "pendiente", comments: [] },
        ],
        submittedAt: daysAgo(3, 15, 0),
        reviewedAt: daysAgo(2, 9, 30),
        reviewDecision: "aprobado",
      },
    ],
    execution: {
      progress: 38,
      acceptedByAreaAt: daysAgo(2, 10, 0),
      updates: [
        { id: uid("ex"), at: daysAgo(2, 16, 0), author: AREA_HEADS.mantenimiento, progress: 10, comment: "Iniciada adquisición del motor." },
        { id: uid("ex"), at: daysAgo(1, 11, 0), author: AREA_HEADS.mantenimiento, progress: 25, comment: "Motor recibido. Inicio limpieza de filtros." },
        { id: uid("ex"), at: daysAgo(0, 9, 30), author: AREA_HEADS.mantenimiento, progress: 38, comment: "2 de 4 filtros limpiados. Motor listo para instalar." },
      ],
    },
    slaDueDate: daysAhead(5),
    createdAt: daysAgo(6),
  },
];

export const SEED_NOTIFICATIONS: Notification[] = [
  {
    id: uid("nt"),
    caseId: "SOP-08-2026",
    title: "Solicitud de ampliación de plazo",
    body: "SOP-08-2026 · el jefe del área solicita ampliación. Pendiente de decisión de SO.",
    at: new Date().toISOString(),
    read: false,
    audience: "seguridad",
    kind: "warning",
  },
  {
    id: uid("nt"),
    caseId: "SOP-20-2026",
    title: "Caso cerrado - Puerta de andén Javier Prado",
    body: "SOP-20-2026 cerrado exitosamente. Flujo completo demostrable.",
    at: daysAgo(1, 16, 5),
    read: false,
    audience: "seguridad",
    kind: "success",
  },
  {
    id: uid("nt"),
    caseId: "SOP-19-2026",
    title: "Caso crítico nuevo - Caída de pasajero",
    body: "Caída de pasajero en escalera mecánica estación San Juan de Dios — prioridad crítica.",
    at: daysAgo(1, 8, 20),
    read: false,
    audience: "seguridad",
    kind: "critical",
  },
  {
    id: uid("nt"),
    caseId: "SOP-17-2026",
    title: "Falla en sistema de frenado - Tren 102",
    body: "Falla en frenado de emergencia en estación Miguel Grau. Servicio suspendido 25 minutos.",
    at: daysAgo(3, 17, 0),
    read: false,
    audience: "seguridad",
    kind: "critical",
  },
  {
    id: uid("nt"),
    caseId: "SOP-16-2026",
    title: "Fuga de agua en túnel Angamos–San Borja",
    body: "Filtración detectada en túnel. Plan de acción propuesto por Infraestructura.",
    at: daysAgo(1, 16, 30),
    read: false,
    audience: "both",
    kind: "warning",
  },
  {
    id: uid("nt"),
    caseId: "SOP-14-2026",
    title: "Caso derivado a Mantenimiento",
    body: "Se asignó SOP-14-2026 a Jorge Salazar. Correo enviado.",
    at: daysAgo(1, 9, 30),
    read: false,
    audience: "both",
    kind: "success",
  },
  {
    id: uid("nt"),
    caseId: "SOP-11-2026",
    title: "Plan de acción aprobado",
    body: "El plan para SOP-11-2026 fue aprobado. Inicia ejecución.",
    at: daysAgo(3, 9, 30),
    read: true,
    audience: "both",
    kind: "success",
  },
];



